FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    wget curl unzip git ant \
    mariadb-client \
    gnupg software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# Java Temurin 25
RUN wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor -o /usr/share/keyrings/adoptium.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/adoptium.gpg] https://packages.adoptium.net/artifactory/deb jammy main" > /etc/apt/sources.list.d/adoptium.list && \
    apt update && apt install -y temurin-25-jdk

ENV JAVA_HOME=/usr/lib/jvm/temurin-25-jdk-amd64

WORKDIR /opt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]